import{a as g}from"./assets/vendor-34f890c2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const b=function(e){return e.map(({views:t,comments:r,downloads:n,likes:o,webformatURL:s,tags:a,largeImageURL:h})=>`<li>
        <div class="img-box">
        <a href="${h}">
        <img class="img" src="${s}" alt="${a}" width="360" height="200">
        </a>
        <ul class="value-list">
        <li class="likes value-item"><p class="article">Likes</p><p class="value">${o}</p></li>
        <li class="views value-item" ><p class="article">Views</p><p class="value">${t}</p></li>
        <li class="comments value-item"><p class="article">Comments</p><p class="value">${r}</p></li>
        <li class="downloads value-item"><p class="article">Downloads</p><p class="value">${n}</p></li>
        </ul></div>
        </li>`).join("")},v="https://pixabay.com/api/",C="43500562-b59296b97b4360198cb07a703";async function d(e,t){const{data:r}=await g(`${v}`,{params:{key:C,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return r}const w=document.querySelector(".search-form"),L=document.querySelector("input"),m=document.querySelector(".object-list"),i=document.querySelector(".loader-box"),c=document.querySelector(".load-more-btn"),O=new simpleLightbox(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250,showCounter:!1});w.addEventListener("submit",S);c.addEventListener("click",$);let l=1,p,u;function S(e){if(e.preventDefault(),!L.value)return iziToast.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",closeOnClick:!0,position:"topCenter"});m.textContent="",i.style.display="flex",u=e.currentTarget.elements.search.value.trim(),l=1,d(u,l).then(t=>{if(!t.total)return i.style.display="none",c.style.display="none",iziToast.info({message:"Don't found",closeOnClick:!0,position:"topCenter"});f(t.hits),e.target.reset(),i.style.display="none",c.style.display="block",y(t)}).catch(t=>(i.style.display="none",iziToast.error({message:`${t.message}`,backgroundColor:"red",position:"topCenter"})))}async function $(){i.style.display="flex",l=l+1,await d(u,l).then(e=>{f(e.hits);const t=document.querySelector("li"),{height:r}=t.getBoundingClientRect();q(r*2,0),i.style.display="none",p=Math.floor(e.totalHits/15),l>=p&&(y(e),iziToast.show({titleColor:"white",message:"We're sorry, but you've reached the end of search results!",messageColor:"black",color:"blue",position:"topCenter",timeout:"5000"}))}).catch(e=>(i.style.display="none",iziToast.error({message:`${e.message}`,backgroundColor:"red",position:"topCenter"})))}function f(e){m.insertAdjacentHTML("beforeend",b(e)),O.refresh()}function q(e=0,t=0){window.scrollBy({top:e,left:t,behavior:"smooth"})}function y(e){Math.round(e.totalHits/l)<=15&&(c.style.display="none")}
//# sourceMappingURL=commonHelpers.js.map
